<?php
// Practical Assessment System - Database Backup Generator
// Zeal College of Engineering & Research

ini_set('memory_limit', '1024M');
ini_set('max_execution_time', '300');

require_once __DIR__ . '/../includes/session.php';
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../config/auth.php';
require_once __DIR__ . '/../includes/functions.php';

require_role('admin');

// Handle 1-click Download Trigger
if (isset($_GET['download']) && $_GET['download'] === 'pdf') {
    log_audit($conn, $_SESSION['user_id'], 'admin', 'Database Backup Download', 'system', 'Downloaded database backup report PDF/HTML.');

    // Fetch Database Tables Summary
    $tables = ['users', 'batches', 'faculty_allocations', 'practicals', 'attendance', 'assessment', 'syllabi', 'audit_logs', 'system_settings'];
    
    header('Content-Type: text/html; charset=utf-8');
    ?>
    <!DOCTYPE html>
    <html>
    <head>
      <title>Database Backup Report - <?php echo COLLEGE_NAME; ?></title>
      <style>
        body { font-family: Arial, sans-serif; margin: 2rem; color: #1e293b; line-height: 1.5; }
        .header { text-align: center; border-bottom: 2px solid #1e3a8a; padding-bottom: 1rem; margin-bottom: 1.5rem; }
        .header h1 { margin: 0; color: #1e3a8a; font-size: 1.5rem; }
        .header h2 { margin: 0.25rem 0; font-size: 1.1rem; color: #475569; }
        .meta { display: flex; justify-content: space-between; margin-bottom: 1.5rem; background: #f1f5f9; padding: 1rem; border-radius: 6px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 1.5rem; font-size: 0.85rem; }
        th, td { border: 1px solid #cbd5e1; padding: 6px 10px; text-align: left; }
        th { background: #1e3a8a; color: white; }
        tr { page-break-inside: avoid; }
        tr:nth-child(even) { background: #f8fafc; }
        @media print {
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="no-print" style="margin-bottom: 1rem; text-align: right;">
        <button onclick="window.print();" style="padding: 10px 20px; background: #2563eb; color: white; border: none; border-radius: 5px; cursor: pointer; font-weight: bold;">
          Print / Save as PDF
        </button>
      </div>

      <div class="header">
        <h1><?php echo COLLEGE_NAME; ?></h1>
        <h2><?php echo DEPARTMENT_NAME; ?> &bull; <?php echo APP_NAME; ?></h2>
        <h3>SYSTEM DATABASE BACKUP REPORT</h3>
      </div>

      <div class="meta">
        <div><strong>Generated On:</strong> <?php echo date('d M Y, H:i:s'); ?></div>
        <div><strong>Generated By:</strong> <?php echo sanitize($_SESSION['full_name']); ?> (Admin)</div>
        <div><strong>Database:</strong> practical_assessment_db</div>
      </div>

      <?php foreach ($tables as $t): ?>
        <?php 
          $res = mysqli_query($conn, "SELECT COUNT(*) as cnt FROM `$t`");
          $cnt = 0;
          if ($res && $r = mysqli_fetch_assoc($res)) { $cnt = $r['cnt']; }
        ?>
        <h3>Table: `<?php echo $t; ?>` (Total Records: <?php echo $cnt; ?>)</h3>
        <?php 
          $data_res = mysqli_query($conn, "SELECT * FROM `$t`");
          if ($data_res && mysqli_num_rows($data_res) > 0):
            $fields = mysqli_fetch_fields($data_res);
        ?>
          <table>
            <thead>
              <tr>
                <?php foreach ($fields as $f): ?>
                  <th><?php echo $f->name; ?></th>
                <?php endforeach; ?>
              </tr>
            </thead>
            <tbody>
              <?php while ($row = mysqli_fetch_assoc($data_res)): ?>
                <tr>
                  <?php foreach ($row as $k => $v): ?>
                    <td><?php echo sanitize($v); ?></td>
                  <?php endforeach; ?>
                </tr>
              <?php endwhile; ?>
            </tbody>
          </table>
        <?php else: ?>
          <p style="color: #64748b;">No records found or empty table.</p>
        <?php endif; ?>
      <?php endforeach; ?>
    </body>
    </html>
    <?php
    exit();
}

$page_title = "Database Backup";
include __DIR__ . '/../includes/header.php';
?>

<div class="card" style="max-width: 600px; margin: 2rem auto; text-align: center;">
  <div class="card-header" style="justify-content: center;">
    <h3 class="card-title"><i class="fas fa-database text-primary me-2"></i> System Database Backup</h3>
  </div>

  <div style="padding: 1.5rem 0;">
    <i class="fas fa-file-pdf fa-4x text-accent mb-3" style="color: #38bdf8;"></i>
    <h4 style="margin-bottom: 0.5rem; color: var(--text-primary);">Generate 1-Click Database PDF Backup</h4>
    <p style="color: var(--text-secondary); margin-bottom: 1.5rem; font-size: 0.9rem;">
      Download an immediate, printable PDF snapshot of all tables, schema structures, and registered system records.
    </p>

    <a href="backup.php?download=pdf" target="_blank" class="btn btn-primary btn-lg" style="padding: 0.85rem 2rem; font-weight: 700;">
      <i class="fas fa-download me-2"></i> Download Database PDF Report
    </a>
  </div>
</div>

<?php include __DIR__ . '/../includes/footer.php'; ?>
